apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: servicex-release-int-uproot
  namespace: servicex-int-uproot
spec:
  releaseName: servicex-release-int-uproot
  serviceAccountName: servicex-int-uproot
  chart:
    spec:
      chart: servicex
      sourceRef:
        kind: HelmRepository
        name: servicex-repo
      version: "v1.100.110"
  interval: 60m
  values:
    # Enable deployment of Minio Object Store with this chart - use this if you
    # want to have the option of delivering results as parquet files
    objectStore:
      enabled: true
      internal: true
      publicURL: int-uproot-minio.servicex.ssl-hep.org
      useTLS: false
      useClientTLS: true
    app:
      image: sslhep/servicex_app
      tag: all-newest
      adminEmail: bengal1@illinois.edu
      pullPolicy: Always
      auth: true
      replicas: 1
      logLevel: INFO
      mailgunDomain: servicex.ssl-hep.org
      slackSigningSecret: dummy
      newSignupWebhook: dummy
      ingress:
        enabled: true
        tls:
          enabled: true
          host: servicex-release-int-uproot.servicex.ssl-hep.org
          clusterIssuer: letsencrypt-prod
    rabbitmq:
      nodeselector:
        storage: rook
      metrics:
        enabled: false
        plugins: rabbitmq_prometheus
        podAnnotations:
          prometheus.io/port: '9419'
          prometheus.io/scrape: 'true'
        prometheusRule:
          additionalLabels: {}
          enabled: false
          namespace: ''
          rules: []
        serviceMonitor:
          additionalLabels: {}
          enabled: true
          honorLabels: false
          interval: 30s
      persistence:
        enabled: false
        storageClass: rook-ceph-block
      auth:
        existingErlangSecret: servicex-secrets
        existingPasswordSecret: servicex-secrets
      extraConfiguration: |-
        consumer_timeout = 3600000
    didFinder:
      rucio:
        enabled: true
        image: sslhep/servicex-did-finder
        pullPolicy: Always
        cachePrefix: root://192.170.240.18:1094//
        servicex_latitude: 41.78
        servicex_longitude: -87.7
        memcache:
          enabled: true
          image: memcached
          ttl: 86400
      CERNOpenData:
        enabled: false
        image: sslhep/servicex-did-finder-cernopendata
        pullPolicy: Always
    codeGen:
      enabled: true
      image: sslhep/servicex_code_gen_func_adl_uproot
      pullPolicy: Always
    transformer:
      autoscaler:
        enabled: true
        cpuScaleThreshold: 30
        minReplicas: 10
        maxReplicas: 750
      pullPolicy: Always
      cpuLimit: 1
      defaultTransformerImage: sslhep/servicex_func_adl_uproot_transformer
      defaultTransformerTag: all-newest
    postgres:
      enabled: true
    postgresql:
      primary:
        persistence:
          enabled: false
          storageClass: rook-ceph-block
        nodeSelector:
          kernel-ml: 'true'
          storage: rook
      global:
        postgresql:
          auth:
            database: servicex
            existingSecret: servicex-secrets
            secretKeys:
              adminPasswordKey: postgresql-password
    minio:
      auth:
        existingSecret: servicex-secrets
      tls:
        enabled: false
      service:
        ports:
          api: 9000
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: letsencrypt-prod
          acme.cert-manager.io/http01-edit-in-place: 'true'
        hostname: int-uproot-minio-console.servicex.ssl-hep.org
        tls: true
      apiIngress:
        enabled: true
        tls: true
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: letsencrypt-prod
          acme.cert-manager.io/http01-edit-in-place: 'true'
        hostname: int-uproot-minio.servicex.ssl-hep.org
    gridAccount: ivukotic
    rbacEnabled: true
    secrets: servicex-secrets
